### PR TITLE
proper original image optimization

### PR DESCRIPTION
**Pull request by buddhaCode**
I the current implementation is a but clumsy. You're not just optimizing the current image, you're optimizing the latest 10 images?!?
I think moving this to the media prePersist event is more elegant.

### CODE REVIEW

**Comment by buddhaCode** [comment]
this would also fix issue #1

**Comment by tinect** [comment]
Hey @buddhaCode 

Thank you! I agree this is a bit clumsy.
The goal with current solution is, that there is a check, which images weren't optimized yet.

So with every optimizing, up to additional 10 not optimized original images, will be processed, too.

With your change this `feature` will be off.

Let me think about it :-)

**Comment by buddhaCode** [comment]
I see. But this can easily fixed by running the optimize console job?!? But I guess you also rely on the free tiny png account with a 500 images limit? This wouldn’t work with the console job.

**Comment by buddhaCode** [comment]
Hey @tinect,
any new thoughts here?

**Comment by shyim** [comment]
Thanks! :)

**Pull request merged**
